---
 - group:
     name: apt-cacher-ng

 - user:
     name: apt-cacher-ng
     shell: '/bin/false'
     group: apt-cacher-ng
     home: '{{ acgn_cachepath }}'
     system: yes

 - name: directory for caching
   file:
     state: directory
     owner: apt-cacher-ng 
     group: apt-cacher-ng 
     path: '{{ acgn_cachepath }}'

 - name: install apt-cacher-ng
   package:
     name: '{{ item }}'
   with_items: '{{ acgn_packages }}'
